language: python
sudo: required
dist: trusty
python: '3.6'

# before_install:

cache:
    - pip

env:
  - APP_SETTINGS=TestingConfig

install:
    - pip install pipenv
    - pipenv install --dev --deploy

script:
    - pipenv run py.test tests/ --cov=frontstage_api
    - pipenv check --style .

after_success:
    - pipenv run codecov

branches:
    only:
        - master
