language: python
sudo: required
dist: trusty
python: '3.4'

# before_install:

cache:
    - pip

install:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - pip install codecov
    - pip install pytest-cov

script:
    - py.test tests/ --cov=frontstage_api

after_success:
    - codecov

branches:
    only:
        - master
